import ConvexClientProvider from "@/components/convex-client-provider";
import { Button } from "@/components/ui/button";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
} from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider>
          <ConvexClientProvider>
            <SignedIn>{children}</SignedIn>
            <SignedOut>
              <main className="flex items-center justify-center h-screen p-4">
                <SignInButton>
                  <Button className="w-full rounded-full">Sign in</Button>
                </SignInButton>
              </main>
            </SignedOut>
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
